export const footballTeams = [
  { name: 'Arsenal', logo: 'https://media.api-sports.io/football/teams/42.png' },
  { name: 'Aston Villa', logo: 'https://media.api-sports.io/football/teams/66.png' },
  { name: 'Bournemouth', logo: 'https://media.api-sports.io/football/teams/35.png' },
  { name: 'Brentford', logo: 'https://media.api-sports.io/football/teams/55.png' },
  { name: 'Brighton', logo: 'https://media.api-sports.io/football/teams/51.png' },
  { name: 'Chelsea', logo: 'https://media.api-sports.io/football/teams/49.png' },
  { name: 'Crystal Palace', logo: 'https://media.api-sports.io/football/teams/52.png' },
  { name: 'Everton', logo: 'https://media.api-sports.io/football/teams/45.png' },
  { name: 'Fulham', logo: 'https://media.api-sports.io/football/teams/36.png' },
  { name: 'Liverpool', logo: 'https://media.api-sports.io/football/teams/40.png' },
  { name: 'Luton Town', logo: 'https://media.api-sports.io/football/teams/1359.png' },
  { name: 'Manchester City', logo: 'https://media.api-sports.io/football/teams/50.png' },
  { name: 'Manchester United', logo: 'https://media.api-sports.io/football/teams/33.png' },
  { name: 'Newcastle', logo: 'https://media.api-sports.io/football/teams/34.png' },
  { name: 'Nottm Forest', logo: 'https://media.api-sports.io/football/teams/65.png' },
  { name: 'Sheffield Utd', logo: 'https://media.api-sports.io/football/teams/62.png' },
  { name: 'Tottenham', logo: 'https://media.api-sports.io/football/teams/47.png' },
  { name: 'West Ham', logo: 'https://media.api-sports.io/football/teams/48.png' },
  { name: 'Wolves', logo: 'https://media.api-sports.io/football/teams/39.png' },
  { name: 'Real Madrid', logo: 'https://media.api-sports.io/football/teams/541.png' },
  { name: 'Barcelona', logo: 'https://media.api-sports.io/football/teams/529.png' },
  { name: 'Atletico Madrid', logo: 'https://media.api-sports.io/football/teams/530.png' },
  { name: 'Girona', logo: 'https://media.api-sports.io/football/teams/547.png' },
  { name: 'Athletic Club', logo: 'https://media.api-sports.io/football/teams/531.png' },
  { name: 'Real Sociedad', logo: 'https://media.api-sports.io/football/teams/548.png' },
  { name: 'Bayern Munich', logo: 'https://media.api-sports.io/football/teams/157.png' },
  { name: 'Borussia Dortmund', logo: 'https://media.api-sports.io/football/teams/165.png' },
  { name: 'Bayer Leverkusen', logo: 'https://media.api-sports.io/football/teams/168.png' },
  { name: 'RB Leipzig', logo: 'https://media.api-sports.io/football/teams/173.png' },
  { name: 'Stuttgart', logo: 'https://media.api-sports.io/football/teams/172.png' },
  { name: 'Juventus', logo: 'https://media.api-sports.io/football/teams/496.png' },
  { name: 'AC Milan', logo: 'https://media.api-sports.io/football/teams/489.png' },
  { name: 'Inter', logo: 'https://media.api-sports.io/football/teams/505.png' },
  { name: 'Napoli', logo: 'https://media.api-sports.io/football/teams/492.png' },
  { name: 'AS Roma', logo: 'https://media.api-sports.io/football/teams/497.png' },
  { name: 'Lazio', logo: 'https://media.api-sports.io/football/teams/487.png' },
  { name: 'Atalanta', logo: 'https://media.api-sports.io/football/teams/499.png' },
  { name: 'Paris Saint Germain', logo: 'https://media.api-sports.io/football/teams/85.png' },
  { name: 'Marseille', logo: 'https://media.api-sports.io/football/teams/81.png' },
  { name: 'Lyon', logo: 'https://media.api-sports.io/football/teams/80.png' },
  { name: 'Monaco', logo: 'https://media.api-sports.io/football/teams/79.png' },
  { name: 'Lille', logo: 'https://media.api-sports.io/football/teams/78.png' },
  { name: 'Benfica', logo: 'https://media.api-sports.io/football/teams/211.png' },
  { name: 'Porto', logo: 'https://media.api-sports.io/football/teams/212.png' },
  { name: 'Sporting CP', logo: 'https://media.api-sports.io/football/teams/228.png' },
  { name: 'Ajax', logo: 'https://media.api-sports.io/football/teams/194.png' },
  { name: 'PSV Eindhoven', logo: 'https://media.api-sports.io/football/teams/197.png' },
  { name: 'Feyenoord', logo: 'https://media.api-sports.io/football/teams/209.png' },
  { name: 'Galatasaray', logo: 'https://media.api-sports.io/football/teams/645.png' },
  { name: 'Fenerbahce', logo: 'https://media.api-sports.io/football/teams/611.png' },
  { name: 'Besiktas', logo: 'https://media.api-sports.io/football/teams/548.png' },
  { name: 'Celtic', logo: 'https://media.api-sports.io/football/teams/247.png' },
  { name: 'Rangers', logo: 'https://media.api-sports.io/football/teams/257.png' },
  { name: 'Boca Juniors', logo: 'https://media.api-sports.io/football/teams/451.png' },
  { name: 'River Plate', logo: 'https://media.api-sports.io/football/teams/435.png' },
  { name: 'Flamengo', logo: 'https://media.api-sports.io/football/teams/127.png' },
  { name: 'Palmeiras', logo: 'https://media.api-sports.io/football/teams/121.png' },
  { name: 'France', logo: 'https://flagcdn.com/w160/fr.png' },
  { name: 'Morocco', logo: 'https://flagcdn.com/w160/ma.png' },
  { name: 'Argentina', logo: 'https://flagcdn.com/w160/ar.png' },
  { name: 'Croatia', logo: 'https://flagcdn.com/w160/hr.png' },
  { name: 'England', logo: 'https://flagcdn.com/w160/gb-eng.png' },
  { name: 'Brazil', logo: 'https://flagcdn.com/w160/br.png' },
  { name: 'Portugal', logo: 'https://flagcdn.com/w160/pt.png' },
  { name: 'Netherlands', logo: 'https://flagcdn.com/w160/nl.png' },
  { name: 'Spain', logo: 'https://flagcdn.com/w160/es.png' },
  { name: 'Germany', logo: 'https://flagcdn.com/w160/de.png' },
  { name: 'Italy', logo: 'https://flagcdn.com/w160/it.png' },
  { name: 'Belgium', logo: 'https://flagcdn.com/w160/be.png' },
  { name: 'Egypt', logo: 'https://flagcdn.com/w160/eg.png' },
  { name: 'CSKA', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/27/CSKA_Sofia_logo.svg/300px-CSKA_Sofia_logo.svg.png' },
  { name: 'Derry City', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ab/Derry_City_FC_logo.svg/300px-Derry_City_FC_logo.svg.png' },
  { name: 'Ipswich', logo: 'https://r2.thesportsdb.com/images/media/team/badge/8wvpj61701761979.png' },
  { name: 'Leicester', logo: 'https://r2.thesportsdb.com/images/media/team/badge/wo3udr1586957093.png' },
  { name: 'Nottingham Forest', logo: 'https://r2.thesportsdb.com/images/media/team/badge/1i2kvh1719918076.png' },
  { name: 'Southampton', logo: 'https://r2.thesportsdb.com/images/media/team/badge/ggqtd01621593274.png' },
  { name: 'Burnley', logo: 'https://r2.thesportsdb.com/images/media/team/badge/ql7nl31686893820.png' },
  { name: 'Real Betis', logo: 'https://r2.thesportsdb.com/images/media/team/badge/2oqulv1663245386.png' },
  { name: 'Villarreal', logo: 'https://r2.thesportsdb.com/images/media/team/badge/vrypqy1473503073.png' },
  { name: 'Valencia', logo: 'https://r2.thesportsdb.com/images/media/team/badge/dm8l6o1655594864.png' },
  { name: 'Sevilla', logo: 'https://r2.thesportsdb.com/images/media/team/badge/vpsqqx1473502977.png' },
  { name: 'Osasuna', logo: 'https://r2.thesportsdb.com/images/media/team/badge/rvspvt1473502960.png' },
  { name: 'Celta Vigo', logo: 'https://r2.thesportsdb.com/images/media/team/badge/xfjtku1690436219.png' },
  { name: 'Mallorca', logo: 'https://r2.thesportsdb.com/images/media/team/badge/ssptsx1473503730.png' },
  { name: 'Getafe', logo: 'https://r2.thesportsdb.com/images/media/team/badge/eyh2891655594452.png' },
  { name: 'Alaves', logo: 'https://r2.thesportsdb.com/images/media/team/badge/0aaifo1734673843.png' },
  { name: 'Las Palmas', logo: 'https://r2.thesportsdb.com/images/media/team/badge/mmhyb11616443601.png' },
  { name: 'Rayo Vallecano', logo: 'https://r2.thesportsdb.com/images/media/team/badge/nzhu941655595465.png' },
  { name: 'Leganes', logo: 'https://r2.thesportsdb.com/images/media/team/badge/tm0adr1616443898.png' },
  { name: 'Valladolid', logo: 'https://r2.thesportsdb.com/images/media/team/badge/guqal21757526050.png' },
  { name: 'Espanyol', logo: 'https://r2.thesportsdb.com/images/media/team/badge/867nzz1681703222.png' },
  { name: 'Bologna', logo: 'https://r2.thesportsdb.com/images/media/team/badge/2qi1u31655592366.png' },
  { name: 'Fiorentina', logo: 'https://r2.thesportsdb.com/images/media/team/badge/hc8nhu1656098030.png' },
  { name: 'Torino', logo: 'https://r2.thesportsdb.com/images/media/team/badge/xxprty1448806802.png' },
  { name: 'Monza', logo: 'https://r2.thesportsdb.com/images/media/team/badge/bxearg1603170113.png' },
  { name: 'Genoa', logo: 'https://r2.thesportsdb.com/images/media/team/badge/52s8dn1655553600.png' },
  { name: 'Lecce', logo: 'https://r2.thesportsdb.com/images/media/team/badge/j4vznr1567365249.png' },
  { name: 'Udinese', logo: 'https://r2.thesportsdb.com/images/media/team/badge/vwvstr1448806811.png' },
  { name: 'Verona', logo: 'https://r2.thesportsdb.com/images/media/team/badge/ti1upd1645219152.png' },
  { name: 'Cagliari', logo: 'https://r2.thesportsdb.com/images/media/team/badge/wvsvxt1447534471.png' },
  { name: 'Empoli', logo: 'https://r2.thesportsdb.com/images/media/team/badge/c1ie6b1622561483.png' },
  { name: 'Parma', logo: 'https://r2.thesportsdb.com/images/media/team/badge/6yiaxs1627406063.png' },
  { name: 'Como', logo: 'https://ui-avatars.com/api/?name=Como&background=18181b&color=fff' },
  { name: 'Venezia', logo: 'https://ui-avatars.com/api/?name=Venezia&background=18181b&color=fff' },
  { name: 'Eintracht Frankfurt', logo: 'https://ui-avatars.com/api/?name=Eintracht%20Frankfurt&background=18181b&color=fff' },
  { name: 'Hoffenheim', logo: 'https://ui-avatars.com/api/?name=Hoffenheim&background=18181b&color=fff' },
  { name: 'Heidenheim', logo: 'https://ui-avatars.com/api/?name=Heidenheim&background=18181b&color=fff' },
  { name: 'Werder Bremen', logo: 'https://ui-avatars.com/api/?name=Werder%20Bremen&background=18181b&color=fff' },
  { name: 'Freiburg', logo: 'https://ui-avatars.com/api/?name=Freiburg&background=18181b&color=fff' },
  { name: 'Augsburg', logo: 'https://ui-avatars.com/api/?name=Augsburg&background=18181b&color=fff' },
  { name: 'Wolfsburg', logo: 'https://ui-avatars.com/api/?name=Wolfsburg&background=18181b&color=fff' },
  { name: 'Mainz', logo: 'https://ui-avatars.com/api/?name=Mainz&background=18181b&color=fff' },
  { name: 'Borussia Monchengladbach', logo: 'https://ui-avatars.com/api/?name=Borussia%20Monchengladbach&background=18181b&color=fff' },
  { name: 'Union Berlin', logo: 'https://ui-avatars.com/api/?name=Union%20Berlin&background=18181b&color=fff' },
  { name: 'Bochum', logo: 'https://ui-avatars.com/api/?name=Bochum&background=18181b&color=fff' },
  { name: 'St Pauli', logo: 'https://ui-avatars.com/api/?name=St%20Pauli&background=18181b&color=fff' },
  { name: 'Holstein Kiel', logo: 'https://ui-avatars.com/api/?name=Holstein%20Kiel&background=18181b&color=fff' },
  { name: 'Brest', logo: 'https://ui-avatars.com/api/?name=Brest&background=18181b&color=fff' },
  { name: 'Nice', logo: 'https://ui-avatars.com/api/?name=Nice&background=18181b&color=fff' },
  { name: 'Lens', logo: 'https://ui-avatars.com/api/?name=Lens&background=18181b&color=fff' },
  { name: 'Rennes', logo: 'https://ui-avatars.com/api/?name=Rennes&background=18181b&color=fff' },
  { name: 'Toulouse', logo: 'https://ui-avatars.com/api/?name=Toulouse&background=18181b&color=fff' },
  { name: 'Montpellier', logo: 'https://ui-avatars.com/api/?name=Montpellier&background=18181b&color=fff' },
  { name: 'Strasbourg', logo: 'https://ui-avatars.com/api/?name=Strasbourg&background=18181b&color=fff' },
  { name: 'Nantes', logo: 'https://ui-avatars.com/api/?name=Nantes&background=18181b&color=fff' },
  { name: 'Le Havre', logo: 'https://ui-avatars.com/api/?name=Le%20Havre&background=18181b&color=fff' },
  { name: 'Auxerre', logo: 'https://ui-avatars.com/api/?name=Auxerre&background=18181b&color=fff' },
  { name: 'Angers', logo: 'https://ui-avatars.com/api/?name=Angers&background=18181b&color=fff' },
  { name: 'Saint-Etienne', logo: 'https://ui-avatars.com/api/?name=Saint-Etienne&background=18181b&color=fff' },
  { name: 'Braga', logo: 'https://ui-avatars.com/api/?name=Braga&background=18181b&color=fff' },
  { name: 'Vitoria de Guimaraes', logo: 'https://ui-avatars.com/api/?name=Vitoria%20de%20Guimaraes&background=18181b&color=fff' },
  { name: 'Moreirense', logo: 'https://ui-avatars.com/api/?name=Moreirense&background=18181b&color=fff' },
  { name: 'Arouca', logo: 'https://ui-avatars.com/api/?name=Arouca&background=18181b&color=fff' },
  { name: 'Famalicao', logo: 'https://ui-avatars.com/api/?name=Famalicao&background=18181b&color=fff' },
  { name: 'Casa Pia', logo: 'https://ui-avatars.com/api/?name=Casa%20Pia&background=18181b&color=fff' },
  { name: 'Farense', logo: 'https://ui-avatars.com/api/?name=Farense&background=18181b&color=fff' },
  { name: 'Rio Ave', logo: 'https://ui-avatars.com/api/?name=Rio%20Ave&background=18181b&color=fff' },
  { name: 'Gil Vicente', logo: 'https://ui-avatars.com/api/?name=Gil%20Vicente&background=18181b&color=fff' },
  { name: 'Estoril', logo: 'https://ui-avatars.com/api/?name=Estoril&background=18181b&color=fff' },
  { name: 'Estrela', logo: 'https://ui-avatars.com/api/?name=Estrela&background=18181b&color=fff' },
  { name: 'Boavista', logo: 'https://ui-avatars.com/api/?name=Boavista&background=18181b&color=fff' },
  { name: 'Nacional', logo: 'https://ui-avatars.com/api/?name=Nacional&background=18181b&color=fff' },
  { name: 'Santa Clara', logo: 'https://ui-avatars.com/api/?name=Santa%20Clara&background=18181b&color=fff' },
  { name: 'AVS', logo: 'https://ui-avatars.com/api/?name=AVS&background=18181b&color=fff' },
  { name: 'Twente', logo: 'https://ui-avatars.com/api/?name=Twente&background=18181b&color=fff' },
  { name: 'AZ Alkmaar', logo: 'https://ui-avatars.com/api/?name=AZ%20Alkmaar&background=18181b&color=fff' },
  { name: 'NEC', logo: 'https://ui-avatars.com/api/?name=NEC&background=18181b&color=fff' },
  { name: 'Utrecht', logo: 'https://ui-avatars.com/api/?name=Utrecht&background=18181b&color=fff' },
  { name: 'Sparta Rotterdam', logo: 'https://ui-avatars.com/api/?name=Sparta%20Rotterdam&background=18181b&color=fff' },
  { name: 'Go Ahead Eagles', logo: 'https://ui-avatars.com/api/?name=Go%20Ahead%20Eagles&background=18181b&color=fff' },
  { name: 'Heerenveen', logo: 'https://ui-avatars.com/api/?name=Heerenveen&background=18181b&color=fff' },
  { name: 'PEC Zwolle', logo: 'https://ui-avatars.com/api/?name=PEC%20Zwolle&background=18181b&color=fff' },
  { name: 'Almere City', logo: 'https://ui-avatars.com/api/?name=Almere%20City&background=18181b&color=fff' },
  { name: 'Heracles', logo: 'https://ui-avatars.com/api/?name=Heracles&background=18181b&color=fff' },
  { name: 'Fortuna Sittard', logo: 'https://ui-avatars.com/api/?name=Fortuna%20Sittard&background=18181b&color=fff' },
  { name: 'RKC Waalwijk', logo: 'https://ui-avatars.com/api/?name=RKC%20Waalwijk&background=18181b&color=fff' },
  { name: 'Willem II', logo: 'https://ui-avatars.com/api/?name=Willem%20II&background=18181b&color=fff' },
  { name: 'Groningen', logo: 'https://ui-avatars.com/api/?name=Groningen&background=18181b&color=fff' },
  { name: 'NAC Breda', logo: 'https://ui-avatars.com/api/?name=NAC%20Breda&background=18181b&color=fff' },
  { name: 'Hearts', logo: 'https://ui-avatars.com/api/?name=Hearts&background=18181b&color=fff' },
  { name: 'Kilmarnock', logo: 'https://ui-avatars.com/api/?name=Kilmarnock&background=18181b&color=fff' },
  { name: 'St Mirren', logo: 'https://ui-avatars.com/api/?name=St%20Mirren&background=18181b&color=fff' },
  { name: 'Dundee', logo: 'https://ui-avatars.com/api/?name=Dundee&background=18181b&color=fff' },
  { name: 'Aberdeen', logo: 'https://ui-avatars.com/api/?name=Aberdeen&background=18181b&color=fff' },
  { name: 'Hibernian', logo: 'https://ui-avatars.com/api/?name=Hibernian&background=18181b&color=fff' },
  { name: 'Motherwell', logo: 'https://ui-avatars.com/api/?name=Motherwell&background=18181b&color=fff' },
  { name: 'St Johnstone', logo: 'https://ui-avatars.com/api/?name=St%20Johnstone&background=18181b&color=fff' },
  { name: 'Ross County', logo: 'https://ui-avatars.com/api/?name=Ross%20County&background=18181b&color=fff' },
  { name: 'Dundee United', logo: 'https://ui-avatars.com/api/?name=Dundee%20United&background=18181b&color=fff' },
  { name: 'Trabzonspor', logo: 'https://ui-avatars.com/api/?name=Trabzonspor&background=18181b&color=fff' },
  { name: 'Istanbul Basaksehir', logo: 'https://ui-avatars.com/api/?name=Istanbul%20Basaksehir&background=18181b&color=fff' },
  { name: 'Ludogorets', logo: 'https://ui-avatars.com/api/?name=Ludogorets&background=18181b&color=fff' },
  { name: 'Levski Sofia', logo: 'https://ui-avatars.com/api/?name=Levski%20Sofia&background=18181b&color=fff' },
  { name: 'CSKA Sofia', logo: 'https://ui-avatars.com/api/?name=CSKA%20Sofia&background=18181b&color=fff' },
  { name: 'Botev Plovdiv', logo: 'https://ui-avatars.com/api/?name=Botev%20Plovdiv&background=18181b&color=fff' },
  { name: 'Lokomotiv Plovdiv', logo: 'https://ui-avatars.com/api/?name=Lokomotiv%20Plovdiv&background=18181b&color=fff' },
  { name: 'Cherno More', logo: 'https://ui-avatars.com/api/?name=Cherno%20More&background=18181b&color=fff' },
  { name: 'Slavia Sofia', logo: 'https://ui-avatars.com/api/?name=Slavia%20Sofia&background=18181b&color=fff' },
  { name: 'Beroe', logo: 'https://ui-avatars.com/api/?name=Beroe&background=18181b&color=fff' },
  { name: 'Arda', logo: 'https://ui-avatars.com/api/?name=Arda&background=18181b&color=fff' },
  { name: 'Krumovgrad', logo: 'https://ui-avatars.com/api/?name=Krumovgrad&background=18181b&color=fff' }
];
